name: Email Automation Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-email-agent:
    runs-on: ubuntu-latest

    services:
      ollama_service:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        options: >-
          --name ollama_service
          --health-cmd="curl -f http://localhost:11434/api/version || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      IMAP_SERVER: imap.gmail.com
      SMTP_SERVER: smtp.gmail.com
      OLLAMA_URL: http://localhost:11434/api/generate
      OLLAMA_MODEL: mistral:7b-instruct-v0.2-q4_0
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests

      - name: Dump Ollama service logs for diagnosis
        run: |
          echo "Ollama service container logs:"
          docker logs ollama_service || echo "No logs found"

      - name: Wait for Ollama Service
        id: wait_ollama
        run: |
          echo "Waiting up to 3 minutes for Ollama service to become healthy..."
          for i in {1..36}; do
            STATUS=$(docker inspect --format='{{json .State.Health.Status}}' ollama_service 2>/dev/null || echo "unhealthy")
            if [ "$STATUS" = "\"healthy\"" ]; then
              echo "Ollama service is healthy."
              exit 0
            else
              echo "Still waiting for Ollama... ($i/36) Status: $STATUS"
              sleep 5
            fi
          done
          echo "Ollama service did not become healthy within 3 minutes. Exiting."
          exit 1

      - name: Verify Ollama Service Connectivity
        run: |
          echo "Testing Ollama service endpoint..."
          if curl -f http://localhost:11434/api/version; then
            echo "Ollama service reachable."
          else
            echo "ERROR: Ollama service not reachable at http://localhost
